# Generated by Django 6.0.7 on 2026-07-21 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Victoria Island Branch', max_length=100)),
                ('address', models.TextField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('project_title', models.CharField(help_text='e.g., 4-Bedroom Duplex Construction - Alhaji Musa', max_length=200)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_phase', models.CharField(help_text='e.g., Foundation & Roofing', max_length=100)),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Enter a value from 0 to 100')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., 500sqm Beachfront Land, Lekki', max_length=200)),
                ('property_type', models.CharField(choices=[('LAND', 'Landed Property'), ('RESIDENTIAL', 'Residential House / Duplex'), ('COMMERCIAL', 'Commercial Building')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('location_address', models.TextField()),
                ('is_for_lease', models.BooleanField(default=False, help_text='Check if available for rent/lease')),
                ('virtual_tour_url', models.URLField(blank=True, help_text='360 Virtual Tour Link', null=True)),
                ('main_image_url', models.URLField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Phase 1: Foundation Laying', max_length=150)),
                ('is_completed', models.BooleanField(default=False)),
                ('site_photo_url', models.URLField(blank=True, help_text='Upload latest on-site construction photo', null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core_api.buildproject')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Walkthrough'), ('COMPLETED', 'Inspection Verified'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_unlocked', models.BooleanField(default=False, help_text='Check to allow client to make online payment')),
                ('property_to_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., 2024 Mercedes-Benz G63 AMG', max_length=150)),
                ('brand', models.CharField(max_length=50)),
                ('model_year', models.PositiveIntegerField()),
                ('outright_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('daily_hire_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available for Sale/Hire'), ('HIRED', 'Currently on Hire/Lease'), ('SOLD', 'Sold Out'), ('MAINTENANCE', 'In Maintenance')], default='AVAILABLE', max_length=20)),
                ('main_image_url', models.URLField(help_text='URL for the landing carousel image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_api.branchlocation')),
            ],
        ),
        migrations.CreateModel(
            name='PickupVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('qr_code_string', models.CharField(max_length=100, unique=True)),
                ('is_scanned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.branchlocation')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_api.vehicle')),
            ],
        ),
    ]
