# Generated by Django 4.2.30 on 2026-07-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_userprofile_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_kyc_verified',
            field=models.BooleanField(default=False),
        ),
    ]
