# Generated by Django 4.2.30 on 2026-08-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0008_supportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
