# Generated by Django 4.2.30 on 2026-08-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0009_userprofile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_bounced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
