# Generated by Django 4.2.30 on 2026-08-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0011_property_latitude_property_longitude_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='url',
            field=models.URLField(blank=True, help_text='Fallback image URL when media file is not available', null=True),
        ),
    ]
