# Generated by Django 4.2.30 on 2026-08-03 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_api', '0012_propertyimage_image_alter_propertyimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionbooking',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='agent_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='agent_response',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='agreed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='agreed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='client_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='contact_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Walkthrough'), ('AGENT_OFFERED', 'Agent Offered'), ('CONFIRMED', 'Confirmed by Agent'), ('AWAITING_ADMIN', 'Awaiting Admin Approval'), ('COMPLETED', 'Inspection Verified'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='InspectionBookingMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=100)),
                ('sender_role', models.CharField(choices=[('CLIENT', 'Client'), ('AGENT', 'Agent'), ('ADMIN', 'Admin')], default='CLIENT', max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core_api.inspectionbooking')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
