# Generated by Django 4.2.30 on 2026-08-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0013_inspectionbooking_admin_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short promo title', max_length=120)),
                ('subtitle', models.CharField(blank=True, help_text='Brief supporting copy', max_length=180)),
                ('discount_text', models.CharField(default='5% off', help_text='Offer text such as 5% off or First 50 students', max_length=80)),
                ('cta_text', models.CharField(default='Learn more', max_length=40)),
                ('target_url', models.URLField(blank=True, help_text='Optional target URL for the promo action', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('audience', models.CharField(choices=[('all', 'All visitors'), ('student', 'Students'), ('agent', 'Agents'), ('buyer', 'Buyers')], default='all', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values appear first in the carousel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-updated_at'],
            },
        ),
    ]
