# Generated by Django 4.2.30 on 2026-08-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0014_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_id_images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_matric_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
