# Generated by Django 6.1 on 2026-08-19 14:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0018_userprofile_kyc_workflow_listing_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='duration_unit',
            field=models.CharField(choices=[('year', 'Per year'), ('day', 'Per day'), ('week', 'Per week'), ('month', 'Per month')], default='month', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='map_url',
            field=models.URLField(blank=True, help_text='Google Maps link for inspection or location verification'),
        ),
        migrations.AddField(
            model_name='listing',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('1500.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Landed Property', 'Landed Property'), ('Completed Building', 'Completed Building'), ('Uncompleted Building', 'Uncompleted Building'), ('Residential House', 'Residential House'), ('Duplex', 'Duplex'), ('Apartment', 'Apartment'), ('Service Apartment', 'Service Apartment'), ('Hostel', 'Hostel'), ('Commercial Property', 'Commercial Property'), ('Build from Scratch', 'Build from Scratch'), ('Automotive', 'Automotive')], default='Residential House', max_length=40),
        ),
    ]
