# Generated by Django 6.1 on 2026-08-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0019_listing_duration_unit_listing_map_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='listing_videos/'),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='property_videos/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Property', 'Property'), ('Landed Property', 'Landed Property'), ('Completed Building', 'Completed Building'), ('Uncompleted Building', 'Uncompleted Building'), ('Residential House', 'Residential House'), ('Duplex', 'Duplex'), ('Apartment', 'Apartment'), ('Service Apartment', 'Service Apartment'), ('Hostel', 'Hostel'), ('Commercial Property', 'Commercial Property'), ('Build from Scratch', 'Build from Scratch'), ('Automotive', 'Automotive')], default='Residential House', max_length=40),
        ),
    ]
