# Generated by Django 6.1 on 2026-08-19 15:16

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0020_listingimage_video_propertyimage_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='listing_videos/'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='property_videos/'),
        ),
    ]
