# Generated by Django 6.1 on 2026-08-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0022_hostelbooking_serviceapartmentbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kyc_face_match_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
