# Generated by Django 6.1 on 2026-08-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0023_userprofile_kyc_face_match_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='identity_documents/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity_document_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identity_document_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
