# Generated by Django 6.1 on 2026-08-22 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0024_userprofile_identity_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionbooking',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_bookings', to='core_api.listing'),
        ),
    ]
