# Generated by Django 6.1 on 2026-08-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0026_inspectioninvoice_paymenttransaction_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionbooking',
            name='inspection_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='inspection_location_accuracy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='inspection_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='location_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspectionbooking',
            name='location_consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
