# Generated by Django 6.1 on 2026-08-24 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0028_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionbooking',
            name='property_to_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_api.property'),
        ),
    ]
