# Generated by Django 4.2.30 on 2026-08-27 05:31

import core_api.private_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0029_alter_inspectionbooking_property_to_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='identity_document',
            field=models.FileField(blank=True, null=True, storage=core_api.private_storage.PrivateIdentityDocumentStorage(), upload_to='identity_documents/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_id_image',
            field=models.ImageField(blank=True, null=True, storage=core_api.private_storage.PrivateIdentityDocumentStorage(), upload_to='student_id_images/'),
        ),
    ]
